version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./foodpal.db
      - LM_STUDIO_BASE_URL=${LM_STUDIO_BASE_URL:-http://host.docker.internal:11434}
      - LM_STUDIO_MODEL=${LM_STUDIO_MODEL:-llama3}
      - COMFYUI_SERVER=${COMFYUI_SERVER:-192.168.4.208:8188}
      - ENABLE_IMAGE_GENERATION=${ENABLE_IMAGE_GENERATION:-true}
      - SECRET_KEY=${SECRET_KEY:-foodpal-secret-key-change-in-production}
      - ALLOWED_ORIGINS=["http://localhost:3000","http://frontend:3000"]
    volumes:
      - ./media:/app/media
      - db_data:/app/data
    networks:
      - foodpal-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - foodpal-network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - foodpal-network
    profiles:
      - production

networks:
  foodpal-network:
    driver: bridge

volumes:
  media_data:
  db_data: